import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1778734931756 implements MigrationInterface {
    name = 'InitialSchema1778734931756'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "functions" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, "display_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c16b68177fcec6e85aa50922972" UNIQUE ("name"), CONSTRAINT "PK_203889d2ae5a98ffc137739301e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1147eb1ef07045a3a101be3387" ON "functions" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c16b68177fcec6e85aa5092297" ON "functions" ("name") `);
        await queryRunner.query(`CREATE TABLE "subfunctions" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "function" character varying(100), "description" text, "is_active" boolean NOT NULL DEFAULT true, "display_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "function_id" integer, CONSTRAINT "UQ_a54aa2d3a270fd0f98f3c97dab0" UNIQUE ("name"), CONSTRAINT "PK_d203978866ba6bc946b0556123a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_97b67915147e12eab17f99148f" ON "subfunctions" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a54aa2d3a270fd0f98f3c97dab" ON "subfunctions" ("name") `);
        await queryRunner.query(`CREATE TABLE "roles" ("id" SERIAL NOT NULL, "role_name" character varying(50) NOT NULL, "role_code" character varying(20) NOT NULL, "description" text, "priority" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ac35f51a0f17e3e1fe121126039" UNIQUE ("role_name"), CONSTRAINT "UQ_3feee96f9a604421f24496988db" UNIQUE ("role_code"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e9f58bffa9bdcc402c0438a60c" ON "roles" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "user_id" character varying(50) NOT NULL, "email" character varying(100) NOT NULL, "password_hash" character varying(255) NOT NULL, "full_name" character varying(100) NOT NULL, "department" character varying(100), "phone" character varying(20), "is_active" boolean NOT NULL DEFAULT true, "last_login" TIMESTAMP, "technologies" jsonb DEFAULT '[]'::jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "role_id" integer, CONSTRAINT "UQ_96aac72f1574b88752e9fb00089" UNIQUE ("user_id"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_96aac72f1574b88752e9fb0008" ON "users" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "user_subfunctions" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "subfunction_id" integer NOT NULL, "assigned_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c640bfcb9a074f93cf380e31408" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6029819758d61bbf818145af66" ON "user_subfunctions" ("user_id", "subfunction_id") `);
        await queryRunner.query(`CREATE TABLE "job_descriptions" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "description" text NOT NULL, "subFunction" character varying, "created_by_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e5e847b0af4a4d33cee0ae1b04b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4f847c57eeb8288767f60338e9" ON "job_descriptions" ("created_by_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_67e31a5d8576bccddc2eda7a54" ON "job_descriptions" ("subFunction") `);
        await queryRunner.query(`CREATE INDEX "IDX_73042c93d370ce45baa49df822" ON "job_descriptions" ("title") `);
        await queryRunner.query(`CREATE TYPE "public"."rrfs_requisition_type_enum" AS ENUM('Billable', 'Non-Billable')`);
        await queryRunner.query(`CREATE TYPE "public"."rrfs_priority_enum" AS ENUM('High', 'Medium', 'Low')`);
        await queryRunner.query(`CREATE TYPE "public"."rrfs_status_enum" AS ENUM('draft', 'pending', 'submitted', 'approved', 'declined', 'rejected', 'on-hold', 'in-progress', 'open-for-hiring', 'closed-by-bench', 'closed')`);
        await queryRunner.query(`CREATE TYPE "public"."rrfs_employment_type_enum" AS ENUM('Full-time', 'Contract', 'Part-time')`);
        await queryRunner.query(`CREATE TABLE "rrfs" ("id" SERIAL NOT NULL, "sub_id" character varying(20), "rrf_number" character varying(20), "position_title" character varying(200) NOT NULL, "department" character varying(100), "entity" character varying(100), "organisation" character varying(100), "requisition_type" "public"."rrfs_requisition_type_enum", "customer_name" character varying(200), "non_billable_sub_type" character varying(50), "function" character varying(100), "sub_function" character varying(100), "subfunction_id" integer, "project_name" character varying(200), "headcount" integer NOT NULL DEFAULT '1', "priority" "public"."rrfs_priority_enum" NOT NULL DEFAULT 'Medium', "status" "public"."rrfs_status_enum" NOT NULL DEFAULT 'draft', "job_description" text, "required_skills" text, "preferred_skills" text, "technologies" text, "interview_panel" jsonb DEFAULT '[]'::jsonb, "experience_min" numeric(3,1), "experience_max" numeric(3,1), "budget_min" numeric(12,2), "budget_max" numeric(12,2), "position_type" character varying(50), "work_mode" character varying(50), "employment_type" "public"."rrfs_employment_type_enum" NOT NULL DEFAULT 'Full-time', "location" character varying(200), "urgency_reason" text, "billing_rate" numeric(10,2), "billing_currency" character varying(10), "billing_start_date" TIMESTAMP, "expected_onboarding_date" TIMESTAMP, "created_by_id" integer NOT NULL, "pmo_verified_by_id" integer, "assigned_to_hr_id" integer, "submitted_at" TIMESTAMP, "approved_at" TIMESTAMP, "sent_to_hr_at" TIMESTAMP, "approved_by_id" integer, "approved_by_name" character varying(255), "rejected_at" TIMESTAMP, "declined_at" TIMESTAMP, "declined_by_id" integer, "declined_by_name" character varying(255), "decline_reason" text, "on_hold_by_id" integer, "on_hold_by_name" character varying(255), "closed_at" TIMESTAMP, "closed_by_id" integer, "candidate_name" character varying(255), "joining_date" TIMESTAMP, "closure_status" character varying(255), "close_reason" character varying(50), "internal_rrf_no" character varying(50), "notes" text, "status_history" jsonb DEFAULT '[]'::jsonb, "last_edited_by_id" integer, "last_edited_by_role" character varying(50), "last_edited_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1715e3cedc1cce8fb5c9e107c07" UNIQUE ("sub_id"), CONSTRAINT "UQ_687de113dfa174eb7eb0bbadcd9" UNIQUE ("rrf_number"), CONSTRAINT "UQ_a1b760d341d66e3fc185002c55b" UNIQUE ("internal_rrf_no"), CONSTRAINT "PK_eb132eddce151fbe621610ff0c1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_59c998f8d67552f64662232991" ON "rrfs" ("subfunction_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_459fc245e167c800324a5bb36a" ON "rrfs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_59ac9f6f4dddb2a7e0d8256362" ON "rrfs" ("department") `);
        await queryRunner.query(`CREATE INDEX "IDX_5b720c818604a4306fecde8222" ON "rrfs" ("created_by_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8aefeda33f88ca68257a856c68" ON "rrfs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_687de113dfa174eb7eb0bbadcd" ON "rrfs" ("rrf_number") `);
        await queryRunner.query(`CREATE TYPE "public"."rrf_approvers_approval_level_enum" AS ENUM('L1', 'L2', 'L3', 'final')`);
        await queryRunner.query(`CREATE TYPE "public"."rrf_approvers_approval_status_enum" AS ENUM('pending', 'approved', 'rejected', 'skipped')`);
        await queryRunner.query(`CREATE TABLE "rrf_approvers" ("id" SERIAL NOT NULL, "rrf_id" integer NOT NULL, "user_id" integer NOT NULL, "approval_level" "public"."rrf_approvers_approval_level_enum" NOT NULL, "approval_status" "public"."rrf_approvers_approval_status_enum" NOT NULL DEFAULT 'pending', "approval_order" integer NOT NULL DEFAULT '1', "comments" text, "approved_at" TIMESTAMP, "rejected_at" TIMESTAMP, "is_mandatory" boolean NOT NULL DEFAULT true, "assigned_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_975f81577b3256cba051e958a39" UNIQUE ("rrf_id", "user_id", "approval_level"), CONSTRAINT "PK_c120ea1243fcec051634c73ea47" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d6fdeddc047ab07ab4285ae6af" ON "rrf_approvers" ("approval_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_85bb14e7fa31b959dd3fd4306a" ON "rrf_approvers" ("approval_level") `);
        await queryRunner.query(`CREATE INDEX "IDX_8a14ae2c1ed75044312699caff" ON "rrf_approvers" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a3f28c93a06ae3f1734ddd09c6" ON "rrf_approvers" ("rrf_id") `);
        await queryRunner.query(`CREATE TABLE "rrf_form_configs" ("id" SERIAL NOT NULL, "field_name" character varying(50) NOT NULL, "field_label" character varying(100) NOT NULL, "field_options" jsonb NOT NULL, "field_type" character varying(50) NOT NULL DEFAULT 'dropdown', "is_required" boolean NOT NULL DEFAULT false, "step" integer NOT NULL DEFAULT '1', "section" character varying(100) NOT NULL DEFAULT 'General', "display_order" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c96be0bb0b1bf93b346554ffece" UNIQUE ("field_name"), CONSTRAINT "PK_e6c44a3d7037c4abf57e651b049" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "modules" ("id" SERIAL NOT NULL, "module_name" character varying(100) NOT NULL, "module_code" character varying(50) NOT NULL, "description" text, "parent_module_id" integer, "route_path" character varying(255), "icon" character varying(50), "display_order" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e10bfbd4b8f0bdc8f363ab5757d" UNIQUE ("module_name"), CONSTRAINT "UQ_3369c41e7e5f274b96318c85886" UNIQUE ("module_code"), CONSTRAINT "PK_7dbefd488bd96c5bf31f0ce0c95" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e43f81528a1e06ee00e8ff395c" ON "modules" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" SERIAL NOT NULL, "module_id" integer NOT NULL, "permission_name" character varying(100) NOT NULL, "permission_code" character varying(50) NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0b211b00917290a34b9a3748820" UNIQUE ("module_id", "permission_code"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_67f9ede5c9877307048f957a1c" ON "permissions" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_738f46bb9ac6ea356f1915835d" ON "permissions" ("module_id") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "title" character varying(255) NOT NULL, "message" text NOT NULL, "type" character varying(50) NOT NULL, "priority" character varying(10) NOT NULL DEFAULT 'MEDIUM', "entity_type" character varying(30), "entity_id" integer, "action_url" character varying(500), "channel" character varying(20) NOT NULL DEFAULT 'IN_APP', "status" character varying(20) NOT NULL DEFAULT 'SENT', "is_read" boolean NOT NULL DEFAULT false, "read_at" TIMESTAMP, "metadata" jsonb DEFAULT '{}'::jsonb, "created_by" integer, "dedupe_key" character varying(255), "delivery_attempts" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9341ee0f2140e37e7b9658cd92" ON "notifications" ("dedupe_key") WHERE "dedupe_key" IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_92f5d3a7779be163cbea7916c6" ON "notifications" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_d5ace4f24abe554acb1a919656" ON "notifications" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_aef1c7aef3725068e5540f8f00" ON "notifications" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_310667f935698fcd8cb319113a" ON "notifications" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_af08fad7c04bb85403970afdc1" ON "notifications" ("user_id", "is_read") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("id" SERIAL NOT NULL, "role_id" integer NOT NULL, "permission_id" integer NOT NULL, "granted_at" TIMESTAMP NOT NULL DEFAULT now(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_25d24010f53bb80b78e412c9656" UNIQUE ("role_id", "permission_id"), CONSTRAINT "PK_84059017c90bfcb701b8fa42297" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`ALTER TABLE "subfunctions" ADD CONSTRAINT "FK_f8fe389a9041f937ef5e35447cf" FOREIGN KEY ("function_id") REFERENCES "functions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_subfunctions" ADD CONSTRAINT "FK_3ca20f2d952532dba0ffa22b0e0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_subfunctions" ADD CONSTRAINT "FK_164e19cdec774f64dec62e68ceb" FOREIGN KEY ("subfunction_id") REFERENCES "subfunctions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_descriptions" ADD CONSTRAINT "FK_4f847c57eeb8288767f60338e9a" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rrfs" ADD CONSTRAINT "FK_59c998f8d67552f64662232991f" FOREIGN KEY ("subfunction_id") REFERENCES "subfunctions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rrfs" ADD CONSTRAINT "FK_5b720c818604a4306fecde82227" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rrfs" ADD CONSTRAINT "FK_f573f215762f4950392c23da383" FOREIGN KEY ("pmo_verified_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rrfs" ADD CONSTRAINT "FK_4a1168e5216bdae9f3f36654d23" FOREIGN KEY ("assigned_to_hr_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rrfs" ADD CONSTRAINT "FK_f7a66459bd29f220f28fafe87c5" FOREIGN KEY ("approved_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rrfs" ADD CONSTRAINT "FK_a91cf161f21d745a11d8df547a7" FOREIGN KEY ("declined_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rrfs" ADD CONSTRAINT "FK_9c4c4a9004defed8186a9d6263f" FOREIGN KEY ("on_hold_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rrfs" ADD CONSTRAINT "FK_d6aab671106c842f439c33f5acc" FOREIGN KEY ("closed_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rrfs" ADD CONSTRAINT "FK_c0d9a86f03618f536910434b75e" FOREIGN KEY ("last_edited_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rrf_approvers" ADD CONSTRAINT "FK_a3f28c93a06ae3f1734ddd09c67" FOREIGN KEY ("rrf_id") REFERENCES "rrfs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rrf_approvers" ADD CONSTRAINT "FK_8a14ae2c1ed75044312699caff3" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "FK_738f46bb9ac6ea356f1915835d0" FOREIGN KEY ("module_id") REFERENCES "modules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "FK_738f46bb9ac6ea356f1915835d0"`);
        await queryRunner.query(`ALTER TABLE "rrf_approvers" DROP CONSTRAINT "FK_8a14ae2c1ed75044312699caff3"`);
        await queryRunner.query(`ALTER TABLE "rrf_approvers" DROP CONSTRAINT "FK_a3f28c93a06ae3f1734ddd09c67"`);
        await queryRunner.query(`ALTER TABLE "rrfs" DROP CONSTRAINT "FK_c0d9a86f03618f536910434b75e"`);
        await queryRunner.query(`ALTER TABLE "rrfs" DROP CONSTRAINT "FK_d6aab671106c842f439c33f5acc"`);
        await queryRunner.query(`ALTER TABLE "rrfs" DROP CONSTRAINT "FK_9c4c4a9004defed8186a9d6263f"`);
        await queryRunner.query(`ALTER TABLE "rrfs" DROP CONSTRAINT "FK_a91cf161f21d745a11d8df547a7"`);
        await queryRunner.query(`ALTER TABLE "rrfs" DROP CONSTRAINT "FK_f7a66459bd29f220f28fafe87c5"`);
        await queryRunner.query(`ALTER TABLE "rrfs" DROP CONSTRAINT "FK_4a1168e5216bdae9f3f36654d23"`);
        await queryRunner.query(`ALTER TABLE "rrfs" DROP CONSTRAINT "FK_f573f215762f4950392c23da383"`);
        await queryRunner.query(`ALTER TABLE "rrfs" DROP CONSTRAINT "FK_5b720c818604a4306fecde82227"`);
        await queryRunner.query(`ALTER TABLE "rrfs" DROP CONSTRAINT "FK_59c998f8d67552f64662232991f"`);
        await queryRunner.query(`ALTER TABLE "job_descriptions" DROP CONSTRAINT "FK_4f847c57eeb8288767f60338e9a"`);
        await queryRunner.query(`ALTER TABLE "user_subfunctions" DROP CONSTRAINT "FK_164e19cdec774f64dec62e68ceb"`);
        await queryRunner.query(`ALTER TABLE "user_subfunctions" DROP CONSTRAINT "FK_3ca20f2d952532dba0ffa22b0e0"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "subfunctions" DROP CONSTRAINT "FK_f8fe389a9041f937ef5e35447cf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af08fad7c04bb85403970afdc1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_310667f935698fcd8cb319113a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aef1c7aef3725068e5540f8f00"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d5ace4f24abe554acb1a919656"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_92f5d3a7779be163cbea7916c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9341ee0f2140e37e7b9658cd92"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_738f46bb9ac6ea356f1915835d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_67f9ede5c9877307048f957a1c"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e43f81528a1e06ee00e8ff395c"`);
        await queryRunner.query(`DROP TABLE "modules"`);
        await queryRunner.query(`DROP TABLE "rrf_form_configs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a3f28c93a06ae3f1734ddd09c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a14ae2c1ed75044312699caff"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85bb14e7fa31b959dd3fd4306a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d6fdeddc047ab07ab4285ae6af"`);
        await queryRunner.query(`DROP TABLE "rrf_approvers"`);
        await queryRunner.query(`DROP TYPE "public"."rrf_approvers_approval_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rrf_approvers_approval_level_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_687de113dfa174eb7eb0bbadcd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8aefeda33f88ca68257a856c68"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b720c818604a4306fecde8222"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_59ac9f6f4dddb2a7e0d8256362"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_459fc245e167c800324a5bb36a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_59c998f8d67552f64662232991"`);
        await queryRunner.query(`DROP TABLE "rrfs"`);
        await queryRunner.query(`DROP TYPE "public"."rrfs_employment_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rrfs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rrfs_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rrfs_requisition_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_73042c93d370ce45baa49df822"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_67e31a5d8576bccddc2eda7a54"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f847c57eeb8288767f60338e9"`);
        await queryRunner.query(`DROP TABLE "job_descriptions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6029819758d61bbf818145af66"`);
        await queryRunner.query(`DROP TABLE "user_subfunctions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_96aac72f1574b88752e9fb0008"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9f58bffa9bdcc402c0438a60c"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a54aa2d3a270fd0f98f3c97dab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97b67915147e12eab17f99148f"`);
        await queryRunner.query(`DROP TABLE "subfunctions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c16b68177fcec6e85aa5092297"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1147eb1ef07045a3a101be3387"`);
        await queryRunner.query(`DROP TABLE "functions"`);
    }

}
