export enum NotificationType {
  // RRF Lifecycle
  RRF_CREATED = 'RRF_CREATED',
  RRF_SUBMITTED = 'RRF_SUBMITTED',
  RRF_RESUBMITTED = 'RRF_RESUBMITTED',
  RRF_APPROVED = 'RRF_APPROVED',
  RRF_REJECTED = 'RRF_REJECTED',
  RRF_DECLINED = 'RRF_DECLINED',
  RRF_ON_HOLD = 'RRF_ON_HOLD',
  RRF_OPENED_FOR_HIRING = 'RRF_OPENED_FOR_HIRING',
  RRF_FILLED_BY_BENCH = 'RRF_FILLED_BY_BENCH',
  RRF_CLOSED = 'RRF_CLOSED',
  RRF_UPDATED = 'RRF_UPDATED',
  RRF_DELETED = 'RRF_DELETED',

  // User Management
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_ROLE_CHANGED = 'USER_ROLE_CHANGED',
  USER_ACTIVATED = 'USER_ACTIVATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  USER_SUBFUNCTIONS_CHANGED = 'USER_SUBFUNCTIONS_CHANGED',

  // System
  SYSTEM_ANNOUNCEMENT = 'SYSTEM_ANNOUNCEMENT',
}
